---

- name: Creating Cart Service
  hosts: cart 
  become: yes
  tasks:
    - name: Disable Default Module in Nodejs
      command: dnf module disable nodejs -y

    - name: Enable Nodejs version 20
      command: dnf module enable nodejs:20 -y

    - name: Install Nodejs
      package:
       name: nodejs
       state: present

    - name: Creating System User
      user:
       name: roboshop
       shell: /sbin/nologin
       home: /app
       system: true

    - name: App Diectory Creation
      file:
       path: /app
       state: directory

    - name: Downloading The Code Content
      get_url:
          url: https://roboshop-artifacts.s3.amazonaws.com/cart-v3.zip
          dest: /tmp/cart.zip

    - name: Unzipping The Code
      unarchive:
            src: /tmp/cart.zip
            dest: /app
            remote_src: yes

    - name: Dependenices Installation
      npm:
        path: /app

    - name: Systemctl Service For Cart
      copy:
        src: cart.service
        dest: /etc/systemd/system/cart.service

    - name: Loading The Service - Daemon Reload
      systemd_service:
        daemon_reload: true
        
    - name: Enabing & Starting The Service
      service:
        name: cart
        state: started
        enabled: yes

    
      


