---

- name: Configuring Catalogue Server
  hosts: catalogue
  become: yes
  tasks:
    - name: Disabling Default Nodejs
      command: dnf module disable nodejs -y

    - name: Enabling  Nodejs:20
      command: dnf module enable nodejs:20 -y

    - name: Installing Nodejs
      package:
        name: nodejs
        state: present

    - name: Creating System User
      user:
        name: roboshop
        shell: /sbin/nologin
        system: true
        home: /app

    - name: Creating App Directory
      file:
        path: /app
        state: directory 
 
    - name: Download The Catalogue Code
      get_url: 
        url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
        dest: /tmp/catalogue.zip

    - name: Unzipping The Catalogue Code
      unarchive:
       src: /tmp/catalogue.zip
       dest: /app 
       remote_src: yes # This means file already exist in catalogue server

    - name: Download The Dependencies
      npm:
       path: /app

    - name: Copy Catalogue service
      copy:
        src: catalogue.service
        dest: /etc/systemd/system/catalogue.service

    - name: Daemon Reload
      systemd_service:
        daemon_reload: enabled

    - name: Enabling And Starting catalogue service
      service:
         name: catalogue
         state: started
         enable: yes

   
    - name: Copy Mongodb Repo
      copy:
        src: mongodb.repo
        dest: /etc/yum.repos.d/mongo.repo

    - name: Install MongoDb Client
      package:
        name: mongodb-mongosh
        state: present
      
   # - name: Loading Products Data 
    #  mongodb.mongodb_shell:
    #    file: /app/db/master-data.js
     #   idempotent: yes
     #   login_host: mongodb.devopsaws.store
      


       
       

