---
  - name: Configuring Catalogue Component
    hosts: catalogue
    become: yes
    tasks:
      - name: Disable default nodejs
        command: # there is no module for disabling specific version so we are going with command module
          dnf module disable nodejs -y

      - name: Enable nodejs:20
        command: # there is no module for enabling specific version so we are going with command module
            dnf module enable nodejs:20 -y

      - name: Install nodejs
        package:
          name: nodejs
          state: present

      - name: Creating System User
        user:
           name: roboshop
           shell: /sbin/nologin
           system: true #for system user
           home: /app

      - name: Create App Directory
        file: 
          path: /app
          state: directory

      - name: Download Catalogue code
        get_url:
           url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
           dest: /tmp/catalogue.zip

      - name: Extract catalogue code
        unarchive:
           src: /tmp/catalogue.zip
           dest: /app
           remote_src: yes
     # remote_src :no (default): file is copied from controller then extracted
     # remote_src:yes : file already exists on remote host
          
      - name: Install Dependencies
        community.general.npm:
             path: /app

      - name: Copy catalogue service to system directory
        copy:
          src: catalogue.service
          dest: /etc/systemd/system/catalogue.service
        notify: Reload systemd

      - name: Start & Enable Catalogue Service
        service:
            name: catalogue
            state: started
            enabled: yes

      - name: Copy mongo repo
        copy:
          src: mongo.repo
          dest: /etc/yum.repos.d/mongo.repo

      - name: Install MongoDb client
        package:
            name: mongodb-mongosh
            state: present

      - name: check products loaded or not
        ansible.builtin.command: mongosh --host mongodb.devopsaws.store --eval 'db.getMongo().getDBNames().indexOf("catalogue")'
        register: catalogue_output

      - name: print catalogue output
        ansible.builtin.debug:
          msg: "{{ catalogue_output }}"

      - name: load products
        ansible.builtin.shell: mongosh --host mongodb.devopsaws.store < /app/db/master-data.js
        when: catalogue_output.stdout | int < 0


    handlers:
        - name: Reload systemd
          systemd:
            daemon_reload: true

          