---

- name: Configuring User Server
  hosts: user
  become: yes
  tasks:
    - name: Disable Default Nodejs
      command: dnf module disable nodejs -y

    - name: Enable Nodejs Version:20
      command: dnf module enable nodejs:20 -y

    - name: Install Nodejs
      package:
         name: nodejs
         state: present

    - name: Create System user
      user:
        name: roboshop
        system: true
        home: /app
        shell: /sbin/nologin

    - name: Create APP Directory
      file:
       path: /app
       state: directory

    - name: Download the Application Code
      get_url:
       url: https://roboshop-artifacts.s3.amazonaws.com/user-v3.zip
       dest: /tmp/user.zip

    - name: Unzipping The Code
      unarchive:
         src: /tmp/user.zip
         dest: /app
         remote_src: yes

    - name: Dependencies Install
      npm:
        path: /app
      
    - name: Creating Systemctl Service For User
      copy:
        src: user.service
        dest: /etc/systemd/system/user.service

    - name: Daemon Reload
      systemd_service:
        daemon_reload: true

    - name: Enabling & Restarting The Service
      service:
        name: user
        state: started
        enabled: yes
      
       
        
    

      
